server:
  port: 8080
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: application-service
          uri: http://localhost:8081
          predicates:
            - Path=/application/**