version: '3.1'

services:
  api-gateway:
    image: 'api-gateway:latest'
    container_name: api-gateway
    build:
      context: api-gateway
    ports:
      - "8080:8080"

  application-service:
    image: 'application-service:latest'
    build:
      context: application-service
    ports:
      - "8081:8081"
    container_name: application-service
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/application_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_DB=application_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_SERVER_URL}
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG= org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";
    env_file:
      - .env
  postgres:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      - POSTGRES_DATABASE_URL=jdbc:postgresql://postgres:5432/application_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=application_db


  document-service:
    image: 'document-service:latest'
    container_name: document-service
    build:
      context: document-service
    depends_on:
      - mongodb
    ports:
      - "8082:8082"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_SERVER_URL}
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";
    env_file:
      - .env

  mongodb:
    container_name: mongodb
    image: mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"