server:
  port: 8082

spring:
  #profiles.active: dev
  application.name: document-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/messages
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL}
    properties:
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required "${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
        protocol: SASL_SSL
    consumer:
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: first_topic