server:
  port: 8081

spring:
 # profiles.active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://18.206.245.138:8080/realms/master
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: grateful-finch-8549-eu2-kafka.upstash.io:9092
    properties:
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="Z3JhdGVmdWwtZmluY2gtODU0OSSi5dcyul_0xNbE20pdkPNChxuDOtHCe7wf4po" password="MzA5MDU1ZjItNmM4Ni00ODk5LTliNjYtZGE4NGMzMjA0OTJk";
      security:
        protocol: SASL_SSL
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  application:
    name: application-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/application_db
    username: postgres
    password: 1234
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring-doc:
  swagger-ui:
    url: /openapi


jwt:
  auth:
    converter:
      resource-id: agile-tool
      principle-attribute: preferred_username