server:
  port: 8080


spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://18.206.245.138:8080/realms/master
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: application-service
          uri: http://localhost:8081
          predicates:
            - Path=/application/**